### ISSUE TITLE
VPN Finder quiz always says that my criteria didn't match any VPNs.

### ISSUE THREAD

**Issue by NylaTheWolf** [techlore/website#13]
The VPN Finder seems pretty bugged. No matter which options I choose, I always get the result that my criteria didn't match any VPNs. Only 5 minutes ago when I kept hitting random options to make sure that it was bugged did I get a result, but trying again? Nope. Nothing.

I don't think the answers I chose, including ones where I answered more randomly, were that crazy either. My personal criteria was that I wanted both security and to be able to download stuff, intermediate (sometimes beginner), the 14 eyes isn't black and white and I'm open to using a trusted provided located there, just a few devices simultaneously connected, and a client for Windows, Mac, and iOS. I don't think that these are that unusual haha 😅

I brought it up in the Techlore Discord server, and one other user said that they experienced the same thing, even after trying different combinations. I was redirected here by another user.

Hopefully y'all are able to get it working properly! 👍🏻

**Comment by techlore-official** [comment]
The VPN Finder hasn't been maintained in a long time, and I assume some changes to the VPN chart likely broke it.

Personally, I've grown a bit mixed on the idea of a VPN Finder quiz, since it takes away a large degree of user autonomy and may be TOO simplified for users. Will think over everything, but it's likely the tool will be abandoned in the near future.

**Comment by henryistaken** [comment]
The VPN Finder has been officially deprecated, so I'll be closing this issue. Thanks for the suggestion and sorry it didn't work out.
